// <auto-generated />
namespace Vidly.DataContexts.VidlyMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMembershipTypeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMembershipTypeId));
        
        string IMigrationMetadata.Id
        {
            get { return "201611101030050_AddMembershipTypeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
